version: "3.9"

services:
  db:
    image: postgres:15.4
    container_name: expense-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: expense-backend
    depends_on:
      - db
    environment:
      DB_SERVER: db
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ACTUATOR_REQUIRED_USER: ${ACTUATOR_REQUIRED_USER}
      ACTUATOR_REQUIRED_PASSWORD: ${ACTUATOR_REQUIRED_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      SPRING_PROFILES_ACTIVE: dev
      HEALTH_INTERNAL_HOST: backend
      BACKEND_ENDPOINT: ${BACKEND_ENDPOINT}
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: expense-frontend
    ports:
      - "3000:3000"
