server:
  port: 8080

spring:
  application:
    name: expense-manager

  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:${DB_PORT:5432}/${POSTGRES_DB:expense_manager}
    username: ${POSTGRES_USER:expense}
    password: ${POSTGRES_PASSWORD:expense}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
  flyway:
    enabled: ${FLYWAY_ENABLED:true}

  security:
    actuator-user:
      name: ${ACTUATOR_REQUIRED_USER:username}
      password: ${ACTUATOR_REQUIRED_PASSWORD:password}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174}

jwt:
  secret: ${JWT_SECRET:asmRfM95Mb6XCM7dCIW4nxUExbkR7YWJX9NcwDHV53Hl0lpEKmknNqVbLFNNejgc}
  expiration-ms: ${JWT_EXPIRATION:3600000}

springdoc:
  swagger-ui:
    path: /swagger-ui

info:
  project:
    application: ${spring.application.name}
    version: @project.version@
    javaVendor: ${java.runtime.name}
    javaVersion: ${java.runtime.version}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: ${ACTUATOR_EXPOSURE:health,prometheus}
  endpoint:
    health:
      show-details: always
      enabled: ${ACTUATOR_HEALTH_ENABLED:true}
    prometheus:
      enabled: ${ACTUATOR_PROMETHEUS_ENABLED:true}

logging:
  pattern:
    console: "[%-5level] [${${spring:spring.application.name}}] [%t] [%date{ISO8601}] [%c{1}:%M:%L] [%X{traceId},%X{spanId}] %msg %n"
  level:
    root: ${LOGGING_LEVEL:INFO}
    br:
      com:
        expensemanager: ${LOGGING_LEVEL:DEBUG}