spring:
  datasource:
    url: jdbc:postgresql://db:5432/expense_manager
    username: expense
    password: expense
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

server:
  port: 8080

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174}

jwt:
  secret: ${JWT_SECRET:asmRfM95Mb6XCM7dCIW4nxUExbkR7YWJX9NcwDHV53Hl0lpEKmknNqVbLFNNejgc}
  expiration-ms: ${JWT_EXPIRATION:3600000}